# Generated by Django 4.2.4 on 2023-08-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repliqApp', '0002_company_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicelog',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicelog',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
