# Generated by Django 4.2.4 on 2023-08-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repliqApp', '0004_remove_devicelog_condition_at_return_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used'), ('Damaged', 'Damaged')], max_length=255),
        ),
        migrations.AlterField(
            model_name='devicelog',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
